In [1]:
# Useful additional packages
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

In [2]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

# u gates

In [3]:
q = QuantumRegister(1)
qc = QuantumCircuit(q)
qc.u3(pi/2,pi/2,pi/2,q)
qc.draw()

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The QuantumCircuit.u3 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use QuantumCircuit.u instead, which acts identically. Alternatively, you can decompose u3 in terms of QuantumCircuit.p and QuantumCircuit.sx: u3(ϴ,φ,λ) = p(φ+π) sx p(ϴ+π) sx p(λ) (2 pulses on hardware).
  This is separate from the ipykernel package so we can avoid doing imports until


┌─────────────────┐
q0_0: ┤ U3(π/2,π/2,π/2) ├
      └─────────────────┘

In [4]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 7.07106781e-01+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 4.32978028e-17+7.07106781e-01j, -7.07106781e-01+8.65956056e-17j]])

In [5]:
qc = QuantumCircuit(q)
qc.u2(pi/2,pi/2,q)
qc.draw()

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The QuantumCircuit.u2 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You can use the general 1-qubit gate QuantumCircuit.u instead: u2(φ,λ) = u(π/2, φ, λ). Alternatively, you can decompose it interms of QuantumCircuit.p and QuantumCircuit.sx: u2(φ,λ) = p(π/2+φ) sx p(λ-π/2) (1 pulse on hardware).
  


┌─────────────┐
q0_0: ┤ U2(π/2,π/2) ├
      └─────────────┘

In [6]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 7.07106781e-01+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 4.32978028e-17+7.07106781e-01j, -7.07106781e-01+8.65956056e-17j]])

In [7]:
qc = QuantumCircuit(q)
qc.u1(pi/2,q)
qc.draw()

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The QuantumCircuit.u1 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use the QuantumCircuit.p method instead, which acts identically.
  


┌─────────┐
q0_0: ┤ U1(π/2) ├
      └─────────┘

In [8]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

# Identity gate

Id=u0(1)

In [9]:
qc = QuantumCircuit(q)
qc.id(q)
qc.draw()

┌───┐
q0_0: ┤ I ├
      └───┘

In [10]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

# Pauli gates

X: bit-flip gate

In [11]:
qc = QuantumCircuit(q)
qc.x(q)
qc.draw()

┌───┐
q0_0: ┤ X ├
      └───┘

In [12]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.+0.0000000e+00j, 1.-1.2246468e-16j],
       [1.+0.0000000e+00j, 0.+0.0000000e+00j]])

Y: bit- and phase-flip gate

In [13]:
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q0_0: ┤ Y ├
      └───┘

In [14]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.000000e+00+0.j, -6.123234e-17-1.j],
       [ 6.123234e-17+1.j,  0.000000e+00+0.j]])

Z: phase-flip gate

In [15]:
qc = QuantumCircuit(q)
qc.z(q)
qc.draw()

┌───┐
q0_0: ┤ Z ├
      └───┘

In [16]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.+0.0000000e+00j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])

# Clifford gates

Hadamard gate

In [17]:
qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

┌───┐
q0_0: ┤ H ├
      └───┘

In [18]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.70710678+0.00000000e+00j,  0.70710678-8.65956056e-17j],
       [ 0.70710678+0.00000000e+00j, -0.70710678+8.65956056e-17j]])

S(or, sqrt(Z) phase) gate

In [19]:
qc = QuantumCircuit(q)
qc.s(q)
qc.draw()

┌───┐
q0_0: ┤ S ├
      └───┘

In [20]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

S^dagger (or, conjugate of sqrt(Z) phase) gate

In [21]:
qc = QuantumCircuit(q)
qc.sdg(q)
qc.draw()

┌─────┐
q0_0: ┤ SDG ├
      └─────┘

job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

# C3 gates

T (or, sqrt(S) phase) gate

In [22]:
qc = QuantumCircuit(q)
qc.t(q)
qc.draw()

┌───┐
q0_0: ┤ T ├
      └───┘

In [23]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

T^dagger (or, conjugate of sqrt(S) phase) gate

In [24]:
qc = QuantumCircuit(q)
qc.tdg(q)
qc.draw()

┌─────┐
q0_0: ┤ TDG ├
      └─────┘

In [25]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j]])

# Standard Rotations

Rotaion around X-axis

In [26]:
qc = QuantumCircuit(q)
qc.rx(pi/2,q)
qc.draw()

┌─────────┐
q0_0: ┤ RX(π/2) ├
      └─────────┘

In [27]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 7.07106781e-01+0.j        , -4.32978028e-17-0.70710678j],
       [ 4.32978028e-17-0.70710678j,  7.07106781e-01+0.j        ]])

Rotion around Y-axis

In [28]:
qc = QuantumCircuit(q)
qc.ry(pi/2,q)
qc.draw()

┌─────────┐
q0_0: ┤ RY(π/2) ├
      └─────────┘

In [29]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.70710678+0.j, -0.70710678+0.j],
       [ 0.70710678+0.j,  0.70710678+0.j]])

Rotation around Z-axis

In [30]:
qc = QuantumCircuit(q)
qc.rz(pi/2,q)
qc.draw()

┌─────────┐
q0_0: ┤ RZ(π/2) ├
      └─────────┘

In [31]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.70710678-0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

# Controlled Pauli Gates

Controlled-X (or, controlled-NOT) gate

In [32]:
q = QuantumRegister(2)
qc = QuantumCircuit(q)
qc.cx(q[0],q[1])
qc.draw()

q15_0: ──■──
       ┌─┴─┐
q15_1: ┤ X ├
       └───┘

In [33]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

Controlled Y gate

In [34]:
qc = QuantumCircuit(q)
qc.cy(q[0],q[1])
qc.draw()

q15_0: ──■──
       ┌─┴─┐
q15_1: ┤ Y ├
       └───┘

In [35]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00+0.j,
        6.123234e-17-1.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 1.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j, 0.000000e+00+0.j,
        0.000000e+00+0.j]])

Controlled Z (or, controlled Phase) gate

In [36]:
qc = QuantumCircuit(q)
qc.cz(q[0],q[1])
qc.draw()

q15_0: ─■─
        │ 
q15_1: ─■─

In [37]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.-6.1232340e-17j,  0.+0.0000000e+00j,  0.+0.0000000e+00j,
         0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j,  1.-6.1232340e-17j,  0.+0.0000000e+00j,
         0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j,  0.+0.0000000e+00j,  1.-1.8369702e-16j,
         0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j,  0.+0.0000000e+00j,  0.+0.0000000e+00j,
        -1.+1.8369702e-16j]])

# Controlled Hadamard gate

In [38]:
qc = QuantumCircuit(q)
qc.ch(q[0],q[1])
qc.draw()

q15_0: ──■──
       ┌─┴─┐
q15_1: ┤ H ├
       └───┘

In [39]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.        -5.55111512e-17j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
       [ 0.        +0.00000000e+00j,  0.70710678+0.00000000e+00j,
         0.        +0.00000000e+00j,  0.70710678-1.11022302e-16j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         1.        -1.72254642e-16j,  0.        +0.00000000e+00j],
       [ 0.        +0.00000000e+00j,  0.70710678+0.00000000e+00j,
         0.        +0.00000000e+00j, -0.70710678+1.66533454e-16j]])

# Controlled rotation gates

Controlled rotaion around Z-axis

In [40]:
qc = QuantumCircuit(q)
qc.crz(pi/2,q[0],q[1])
qc.draw()

q15_0: ─────■─────
       ┌────┴────┐
q15_1: ┤ RZ(π/2) ├
       └─────────┘

In [41]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.70710678+0.70710678j]])

# Controlled phase rotation

In [42]:
qc = QuantumCircuit(q)
qc.cu1(pi/2,q[0], q[1])
qc.draw()

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The QuantumCircuit.cu1 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use the QuantumCircuit.cp method instead, which acts identically.
  


q15_0: ─■────
        │π/2 
q15_1: ─■────

In [43]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]])

# Controlled u3 rotation

In [44]:
qc = QuantumCircuit(q)
qc.cu3(pi/2, pi/2, pi/2, q[0], q[1])
qc.draw()

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The QuantumCircuit.cu3 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use the QuantumCircuit.cu method instead, where cu3(ϴ,φ,λ) = cu(ϴ,φ,λ,0).
  


q15_0: ─────────■─────────
       ┌────────┴────────┐
q15_1: ┤ U3(π/2,π/2,π/2) ├
       └─────────────────┘

In [45]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  7.07106781e-01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  4.32978028e-17+7.07106781e-01j,
         0.00000000e+00+0.00000000e+00j, -7.07106781e-01+8.65956056e-17j]])

# SWAP gate

In [46]:
qc = QuantumCircuit(q)
qc.swap(q[0], q[1])
qc.draw()

q15_0: ─X─
        │ 
q15_1: ─X─

In [47]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

# Toffoli Gate (ccx gate)

In [48]:
q = QuantumRegister(3)
qc = QuantumCircuit(q)
qc.ccx(q[0], q[1], q[2])
qc.draw()

q24_0: ──■──
         │  
q24_1: ──■──
       ┌─┴─┐
q24_2: ┤ X ├
       └───┘

In [49]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.-5.55111512e-17j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 1.-5.55111512e-17j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 1.-5.55111512e-17j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 1.-2.84290388e-16j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 1.-2.27765794e-16j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
       

# Controlled swap gate (Fredkin Gate)

In [50]:
qc = QuantumCircuit(q)
qc.cswap(q[0], q[1], q[2])
qc.draw()

q24_0: ─■─
        │ 
q24_1: ─X─
        │ 
q24_2: ─X─

In [51]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.-5.55111512e-17j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 1.-5.55111512e-17j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 1.-5.55111512e-17j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j, 1.-2.84290388e-16j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 1.-2.84290388e-16j, 0.+0.00000000e+00j,
        0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j,
       

# Non-unitary operations

In [52]:
q = QuantumRegister(1)
c = ClassicalRegister(1)

# Measurements

In [53]:
qc = QuantumCircuit(q, c)
qc.measure(q, c)
qc.draw()

┌─┐
q27_0: ┤M├
       └╥┘
 c0: 1/═╩═
        0

In [54]:
backend = BasicAer.get_backend('qasm_simulator')
job = execute(qc, backend, shots=1024)
job.result().get_counts(qc)

{'0': 1024}

In [55]:
qc = QuantumCircuit(q, c)
qc.h(q)
qc.measure(q, c)
qc.draw()

┌───┐┌─┐
q27_0: ┤ H ├┤M├
       └───┘└╥┘
 c0: 1/══════╩═
             0

In [56]:
job = execute(qc, backend, shots=1024)
job.result().get_counts(qc)

{'0': 494, '1': 530}

# Reset

In [57]:
qc = QuantumCircuit(q, c)
qc.reset(q[0])
qc.measure(q, c)
qc.draw()

┌─┐
q27_0: ─|0>─┤M├
            └╥┘
 c0: 1/══════╩═
             0

In [58]:
job = execute(qc, backend, shots=1024)
job.result().get_counts(qc)

{'0': 1024}

In [59]:
qc = QuantumCircuit(q, c)
qc.h(q)
qc.reset(q[0])
qc.measure(q, c)
qc.draw()

┌───┐     ┌─┐
q27_0: ┤ H ├─|0>─┤M├
       └───┘     └╥┘
 c0: 1/═══════════╩═
                  0

In [60]:
job = execute(qc, backend, shots=1024)
job.result().get_counts(qc)

{'0': 1024}

# Conditional operations

In [61]:
qc = QuantumCircuit(q, c)
qc.x(q[0]).c_if(c, 0)
qc.measure(q,c)
qc.draw()

┌───┐ ┌─┐
q27_0: ─┤ X ├─┤M├
        └─┬─┘ └╥┘
       ┌──┴──┐ ║ 
 c0: 1/╡ = 0 ╞═╩═
       └─────┘ 0

In [62]:
job = execute(qc, backend, shots=1024)
job.result().get_counts(qc)

{'1': 1024}

In [63]:
qc = QuantumCircuit(q, c)
qc.h(q)
qc.measure(q,c)
qc.x(q[0]).c_if(c, 0)
qc.measure(q,c)
qc.draw()


┌───┐┌─┐ ┌───┐ ┌─┐
q27_0: ┤ H ├┤M├─┤ X ├─┤M├
       └───┘└╥┘ └─┬─┘ └╥┘
             ║ ┌──┴──┐ ║ 
 c0: 1/══════╩═╡ = 0 ╞═╩═
             0 └─────┘ 0

In [64]:
job = execute(qc, backend, shots=1024)
job.result().get_counts(qc)

{'1': 1024}

# Arbitratry initialization

In [65]:
# Initializing a three-qubit quantum state
import math
desired_vector = [
    1 / math.sqrt(16) * complex(0, 1),
    1 / math.sqrt(8) * complex(1, 0),
    1 / math.sqrt(16) * complex(1, 1),
    0,
    0,
    1 / math.sqrt(8) * complex(1, 2),
    1 / math.sqrt(16) * complex(1, 0),
    0]


q = QuantumRegister(3)

qc = QuantumCircuit(q)

qc.initialize(desired_vector, [q[0],q[1],q[2]])
qc.draw()

┌───────────────────────────────────────────────────────────────────┐
q41_0: ┤0                                                                  ├
       │                                                                   │
q41_1: ┤1 initialize(0.25j,0.35355,0.25+0.25j,0,0,0.35355+0.70711j,0.25,0) ├
       │                                                                   │
q41_2: ┤2                                                                  ├
       └───────────────────────────────────────────────────────────────────┘

In [66]:
backend = BasicAer.get_backend('statevector_simulator')
job = execute(qc, backend)
qc_state = job.result().get_statevector(qc)
qc_state

array([2.50000000e-01+0.j        , 0.00000000e+00-0.35355339j,
       2.50000000e-01-0.25j      , 0.00000000e+00+0.j        ,
       0.00000000e+00+0.j        , 7.07106781e-01-0.35355339j,
       2.77555756e-17-0.25j      , 0.00000000e+00+0.j        ])

In [67]:
#The fidelity is equal to 1 if and only if two states are equal.
state_fidelity(desired_vector,qc_state)

1.0000000000000009